### ISSUE TITLE
Enhancement: Allow Item Positioning Further Back

### ISSUE THREAD

**Issue by jcsnider** [bozzobrain/LethalCompanyShipMaid#10]
It would be nice if we would set item positions to be towards the back wall of the ship so we can place things in the back corner under the screens. Right now it seems like there is a limit and nothing can be placed further back than about where the terminal typically is.

**Comment by bozzobrain** [comment]
This was definitely an oversight from a previous build's intent to not place objects in the back of the ship. WIth manual overriding, I understand the need to remove this limitation. Working on that and will notify when the change is complete.

**Comment by bozzobrain** [comment]
I overhauled the positioning bounds to better match the actual interior of the ship. Let me know if there are any issues in the boundaries. I attempted to make them extend to the walls of the sides and the rear of ship. Thanks for the continued feedback!
