### ISSUE TITLE
Bug - Crash with LGU WheelBarrow

### ISSUE THREAD

**Issue by Pockett-Dev** [bozzobrain/LethalCompanyShipMaid#11]
Hey there,

I've discovered a pretty gnarly crash that occurs when trying to sort items that are inside a Wheelbarrow / Shopping Cart from the LateGameUpgrades mod. My guess for a quick fix might be to have ShipMaid ignore items that are within a Wheelbarrow / Shopping Cart, and sort the Wheelbarrow / Shopping Cart as a two-handed item?

**Comment by bozzobrain** [comment]
Hey @GrantisMantis. First off, thanks for the feedback. 

I am trying to recreate the issue with the wheelbarrow, and havent been able to yet. I appears that my search for items to organize is getting the items in the wheelbarrow, and is pulling them out of the wheelbarrow. The wheelbarrow is recognized as a two-handed item and organized accordingly. 

Can you describe the setup to get the crash you are describing to occur? Is it when specific objects are stored in the wheelbarrow? Does it occur with both the wheelbarrow and shopping cart? Do you have a list of mods that are installed, perhaps its another interaction beyond LateGameUpgrades?  Can you send me a copy of your configuration for ShipMaid to see what interactions may be occuring?

**Comment by GrantisMantis** [comment]
I created this issue with 2 radar boosters being in a Wheelbarrow. Here's a code to my modded profile since I think this would be the best way of providing you with my setup: 018d51db-569a-97f2-f908-5fa8151a0b34

**Comment by bozzobrain** [comment]
I was unable to recreate this issue, but for now I am going to patch out any migration of objects within the wheelbarrow to reduce the likelyhood of the crash. Curious if you have experienced it again or if it was a one-time fluke?

**Comment by GrantisMantis** [comment]
I had the crash twice and then decided to report here - however, ever since this (can't remember if there's been any LGU / ShipMaid updates) I haven't had any crashes! :)

**Comment by bozzobrain** [comment]
Sounds like we will wait for additional issues! Thanks for the response!
