### ISSUE TITLE
Suggestion: randomize drop position by config value

### ISSUE THREAD

**Issue by Jonteiro** [bozzobrain/LethalCompanyShipMaid#14]
Right now, if you sort items with position overrides they will be perfectly stacked on each other which makes them very tidy but makes you unable to quickly see how many of an item you have (1 shovel or 15 shovels appear the same). What i wanted was a config option to specify a value to randomly add or deduct from the item saves coordinates to make the item placement feel a bit more "humane" and make it so you can get an estimate to how many items there are, smaller suggestions related are adding a blacklist for position randomization and if rotation should also be randomized and by how many degrees maximum

**Comment by bozzobrain** [comment]
I totally understand this request. There was an option for this before the override locations subsystem went into effect. It was the [Stack] vs. [Loose] option. I can probably make this config option also apply to the position override system. It was always a bit awkward, but maybe we can go back and forth on optimizing this feature. 

I'll try to get a prototype for this together and we could work on optimizing it.

**Comment by bozzobrain** [comment]
Working on this at the moment. I have a candidate for position randomization. However the game really has a weird thing that it wants to make the objects all fall with the same rotation. Playing with this and maybe I will give up, but for now trying somethings.
