### ISSUE TITLE
Suggestion: Add a physical button or terminal command to cleanup the ship

### ISSUE THREAD

**Issue by UmaLPZ** [bozzobrain/LethalCompanyShipMaid#18]
The mod is great but sometimes we accidentally press in the cleanup keys when typing in chat (or think we are typing in chat) and all the loot gets moved around. This might not be a big deal for most people though so it's completely understandable if it's not worth the time to implement.

**Comment by bozzobrain** [comment]
Thanks for your feedback! Also thanks for separating this issue. I feel like I'm partial to the terminal command, since my knowledge of ingame assets is completely lacking. I may use it as a learning opportunity, but a terminal command would seem lower hanging fruit. I will investigate.

**Comment by bozzobrain** [comment]
Implemented the terminal command and the ability to disable the keybinds for cleanup options. I will say that the set object location keybind is not omitted with the terminal only setting, as I do not have a way to set that without hitting the key while holding an object in location.

Let me know if you see anything broken or wrong with my implementation!

Thanks for the feedback and ideas. As always, keep them coming!
