### ISSUE TITLE
Enhancement: Allow treating shotguns differently based on ammo count.

### ISSUE THREAD

**Issue by jcsnider** [bozzobrain/LethalCompanyShipMaid#19]
Spamming rend lately and we have dozens of shotguns. It might be nice if there was an option to treat shotguns with no ammo differently from shotguns with 1 shell and shotguns with 2 shells so we could have designated areas for all of them.

**Comment by bozzobrain** [comment]
A great suggestion! Let me know what you think of the update and if anything is off! Also thanks for the support @jcsnider!
