### ISSUE TITLE
item location issues

### ISSUE THREAD

**Issue by LordIgnis** [bozzobrain/LethalCompanyShipMaid#2]
is there any way to make it so that items that are organized on the ship aren't clipped into the suit rack? Specifically because with mods like MoreSuits where the entire rack is completely full, having a crap load of items completely inaccessible because they are blocked by the suit change button really sucks, the only way I was able to get around this is because I happen to also use the mods Instant Loot and Cabinet Item Storage, so I could pull the items inside the suit rack off the ship with Instant Loot and then bring them back on the ship to organize them in the drawers of the cabinet.

**Comment by bozzobrain** [comment]
Completely understand. I will patch this issue. Also, I am open to suggestions for better item organization in the ship!

**Comment by bozzobrain** [comment]
Fixed in v2.1.1
