### ISSUE TITLE
Mod doesn't work

### ISSUE THREAD

**Issue by Nzii3** [bozzobrain/LethalCompanyShipMaid#20]
Whenever I enter "cleanup" into the terminal, it doesn't seem like the command even runs. When I click M or N, nothing happens. I do have loot on the ship. The "cleanup storage" command works but I don't use the storage cabinet.

**Comment by Nzii3** [comment]
This also shows in the console when I enter "cleanup" into the terminal
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/106406461/35c46cdd-9b54-4daf-a3a3-fd1380ff8f55)

![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/106406461/3849cf76-12ba-4cba-9b81-e4940cae80d1)

**Comment by Nzii3** [comment]
@bozzobrain

**Comment by bozzobrain** [comment]
I was slightly aware that there was a potential for this issue, and I haven't heard of it happening on other mod users PCs. I felt like this was a result of the mod not getting a proper reference for either localPlayerController or something in the Networking side of things. I'll give this a closer look and see if I can replicate it.

In the meantime, can you let me know your playing conditions (solo / with people), whether you were in a round or in the ship prior to landing, local/online play, only on boot, every boot, etc. Any information to try to replicate would be helpful.

**Comment by bozzobrain** [comment]
I added a release here on github that you can use to get a new debug log for me to see what is actually going on under the hood. Will give me a cleaner look and see if what I see happening is happening. Drop this new mod in the plugin directory and recreate the issue and let me know what you see in the debug! Thanks for reaching out!

**Comment by Nzii3** [comment]
@bozzobrain I tried it solo and playing with multiple people. To get the debug log, do I just update the mod?

**Comment by bozzobrain** [comment]
I didn't release the mod to thunderstorm, it would require you to manually download the latest release and drop it in your steam library folder, under plugins. I'm away from my computer, so if you can try great, otherwise I can help walk you thru when I'm back at my PC.

**Comment by bozzobrain** [comment]
@Nzii3  I actually did upload the updated version with debug to Thunderstore, so updating the mod on there will give you the new debugging option that I would like for you to capture. Please post back when you have that log capture.

**Comment by Nzii3** [comment]
Sounds good, I can get the debug log tonight and send it.

**Comment by Nzii3** [comment]
@bozzobrain Everything seems to work now but the saving a spot to put a specific item isn't working.

https://github.com/bozzobrain/LethalCompanyShipMaid/assets/106406461/6332e1bd-d728-499a-9743-1ee4acd0aeaf

**Comment by Nzii3** [comment]
@bozzobrain It works now, but pressing J to set an specific item's organization spot sometimes doesn't work. Like pressing J doesn't do anything but sometimes it does work.

**Comment by bozzobrain** [comment]
I am curious if this is met with an error in the log at the same time that the issue occurs. If you can give me a logged error at the times that it does not work correctly it will definitely help to solve the issue. 

This is a partially known bug, but I havent seen it occur that often to be able to track it down. Let me know if you get any leads on identifying the issue!

**Comment by bozzobrain** [comment]
Issue is stale, with new release as well I'm closing issue. Please open new issue if problems persist.
