### ISSUE TITLE
Mod does not work when an Override is active. V.50

### ISSUE THREAD

**Issue by AJAL8000** [bozzobrain/LethalCompanyShipMaid#22]
Lest say I press "J" and set the Large Axel in this spot and the general Two-handed scrap.
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/00f21c8a-f510-4c87-8cf0-884df2fc4346)
I use the overrides.
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/029df3cd-af18-464a-9b8a-bb761e65c88e)
The result:
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/631366d7-cc30-4e0e-8ecc-2a970f67893d)
All items move, even if they are 1-handed. Most end up above the ship and outside the ship. Some end up falling back into the ship, which are the ones in the image in this case.
Even if I only activate 1 override, the problem persists.
By removing the overrides, the mod works "correctly".
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/b721196d-8b49-4041-99ce-0e242fee48d0)
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/5f209923-5048-4fc0-9f8d-fad45f15a114)
I'm going to assume that the problem is since the v50 update.

**Comment by bozzobrain** [comment]
Please check this against the latest version released, new binary built with new dlls from V50

**Comment by bozzobrain** [comment]
Due to new release generated, closing issue for now. Will reopen upon request

**Comment by AJAL8000** [comment]
I still see the problem, I'm doing something wrong?

![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/3177f4bb-28b8-4c34-8f15-cee8f70fbfb0)
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/11d59da4-2bfc-4e66-990f-bd27cc27d629)
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/86d9aba7-194f-4992-a878-9838b3e558f2)
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/55171241/bec9ed37-e975-4b15-b130-528a88041245)

**Comment by AJAL8000** [comment]
> Due to new release generated, closing issue for now. Will reopen upon request

I'm literally only using the mods necessary for ShipMaid to work, it seems strange to me that you don't notice the problem because I simply install your mod and I can already see the problem, there is no incompatibility. I honestly don't understand why I get this problem.

I would like you to reopen the Issue.
