### ISSUE TITLE
Enhancement - Item Sorting Black List

### ISSUE THREAD

**Issue by nontheoretical** [bozzobrain/LethalCompanyShipMaid#4]
Similar to the "Cabinet Loot" list I think it would be a good idea to disable sorting of certain items in the config file.

For example, my group actually likes woopie cushions at the front for the laughs, and we have some items that are "Mascots" that we don't want to sell and instead place in certain locations and wish for them to stay there (Ex: Fancy Lights go on the table).

Features Requested:
- Configurable black list in the config file where items can be named to prevent sorting.
- Items on the black list are not considered when sorting items throughout the ship.
- Items not on the black list are sorted normally per the config file.

I'll say I really love this mod, but a sorting black list would make it that much better for how my friends and I play.
Thanks for your hard work!

**Comment by bozzobrain** [comment]
Awesome idea.

Already got it baked in, taking a look at your other bug reports, will close when tested a bit.

Thanks for enjoying the mod and providing your feedback.

**Comment by bozzobrain** [comment]
Enhancement included in V3.0.1+
