### ISSUE TITLE
Bug - Items Sort Outside of Ship Randomly

### ISSUE THREAD

**Issue by nontheoretical** [bozzobrain/LethalCompanyShipMaid#5]
With certain configurations, it's possible for items to sort and respawn outside of the ship.

Configuration File:
- OrganizationMethod = Stack
- TwoHandedItemLocation = Front
- ItemGrouping = Loose
- All other fields = default values

Steps to reproduce:
- Have an assortment of items on the ship.
- Press the M key to sort items.

Result:
- items can clip through the walls and be barely visible
- items can spawn fully outside of the ship and are not accessible

Expected result:
- item spawn locations will be such that all items can easily be seen and grabbed within the ship walls

Screenshots:
- All screenshots taken below were using the config state listed above
- No items are grabbed, replaced, or moves manually between screenshots

Items spawned in a good location:
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/19787039/2758e61d-09b5-4627-a81c-b77fe0e546e6)

Paintings spawn clipping almost all the way out of the ship:
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/19787039/f725b7a9-3c79-439a-9fc0-9d90ee11ced4)

Lamps spawn clipping almost all the way out of the ship:
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/19787039/dc532662-f5fa-49ee-a703-f5a0ebe823ca)

Lamps spawn outside the ship, paintings spawn clipping through the wall:
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/19787039/fc395a3e-8959-47a2-8c3e-e82b9ab2fcd3)

**Comment by bozzobrain** [comment]
First of all, thanks for the detailed report and all the information, it really helps me track things down as well as remain motivated to continue development on this project.

As for the issue, I'm fairly confident that this is a product of my fast and loose method of getting ship coordinates. Investigating now.

**Comment by bozzobrain** [comment]
Curious if you can reproduce this issue with the OrganizationMethod set to Tight. 

Your items do spawn a bit forward of where I expect them to and I think I can fast patch this issue with a slight adjustment in the meantime before potentially overhauling the positioning system. If you can produce this issue with Tight then I have a bigger issue of inconsistent World Coordinates or something of the sort, but if not I think my random number generator is a bit aggressive.

**Comment by bozzobrain** [comment]
Patch was created to prevent any items from sorted outside of the ship, issue has been resolved. Keep the feedback coming and let me know if there are further issues.
