### ISSUE TITLE
Bug - Extremely high value items spawn outside of the ship using sort by value

### ISSUE THREAD

**Issue by nontheoretical** [bozzobrain/LethalCompanyShipMaid#6]
While using other mods that manipulate item values, it's possible for items to sort and respawn outside of the ship.

Configuration File:
- OrganizationMethod = Value
- TwoHandedItemLocation = Front
- ItemGrouping = Loose
- All other fields = default values

Steps to reproduce:
- Have an assortment of items on the ship.
- Have an item or items that are exceptionally high in value. (using for example the [Gambling Machine mod](https://thunderstore.io/c/lethal-company/p/JunLethalCompany/GamblingMachineAtTheCompany/)).
- Press the M key to sort items.

Result:
- items with very high values are sorted outside of the ship.

Expected result:
- max distance from the door is calculated based on the highest value item.
- min distance from the door is calculated based on the lowest value item.
- items are placed relative to the door based on their value relative to each other using the calculated min and max values.

Screenshots:

In this example I have four very high value items:
- Plush value = 240
- Lamp value = 560
- Cube value = 840
- Pickles value = 900

Items with high values before sorting:
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/19787039/c5076505-a9a7-4240-9b47-afe2471b3223)

Items with high values after sorting:
![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/19787039/2b7cfa13-4c28-428c-91d8-f8f995888845)

- the lamp and plush are very far away from the other items
- the cube and pickles are so far from the front door that they have spawned outside of the ship.

**Comment by bozzobrain** [comment]
I know exactly why this is happening. I had a constant value of 200 for the highest expected value. It now is calculated based on the contents of the ship. This should be solved in next release. Upon release, feel free to give it a try.

Thank you so much for the well documented and explained report!

**Comment by bozzobrain** [comment]
Fixed and gave it some  testing, let me know if you see anything else!

**Comment by nontheoretical** [comment]
In an effort to break your update, I did some item value manipulation.
It seems to be working quite well!

Thought you'd get a kick out of this screenshot:

![image](https://github.com/bozzobrain/LethalCompanyShipMaid/assets/19787039/1fa0ce48-4de6-402a-9f9b-08232a3beb53)

**Comment by bozzobrain** [comment]
That loot should give you quite the overtime bonus!

Thank you so much for putting in some time to try to break things! Thats how we make progress and make sure we have the bug fixed. Sounds like this one was correctly closed.

Keep breaking things for me and I'll keep fixing them.

Also if you want to check out the new mod I released: [FireSale](https://github.com/bozzobrain/LethalCompanyFireSale), I would love to get that one debugged and enhanced. Just know that there are a lot of config stuff I want to do with it, but didn't have the time yet.
