### ISSUE TITLE
Enhancement Idea - Location Override Options

### ISSUE THREAD

**Issue by jcsnider** [bozzobrain/LethalCompanyShipMaid#7]
Just an idea, but it would be really cool if we could actually enter coordinates into the config file for where to place the small item and big item piles in relative to the ship of course.

**Comment by bozzobrain** [comment]
I actually have been working on a variation of this. Instead of setting this in a config file I have been working on a means of setting this from a keybind. I was working to make it so that object of a given type can have a location, but I think I extended this to be able to handle one handed or two handed objects. Give it a try and let me know the results.

**Comment by jcsnider** [comment]
Initial results are that the 'J' key doesn't seem to be doing anything. Probably something wrong on my end. My config is below if you have any advice. It does seem like the small objects are now in the back of the ship but I cannot set a location for them.
```
## Settings file was created by plugin ShipMaid v3.2.1
## Plugin GUID: ShipMaid

[ShipMaid]

## Activate ship maid ship keybind.
# Setting type: String
# Default value: <Keyboard>/m
CleanupShipKey = <Keyboard>/m

## Activate ship maid closet keybind.
# Setting type: String
# Default value: <Keyboard>/n
CleanupClosetKey = <Keyboard>/n

## Choose organization method, spread items of a type by [Value] or [Stack] perfectly by item type.
# Setting type: String
# Default value: Value
OrganizationMethod = Stack

## Choose location for two handed objects, [Front] of ship, or [Back] of ship. The opposite location will have the single handed items
# Setting type: String
# Default value: Front
TwoHandedItemLocation = Front

## [Loose] Spread items accross the ship from left to right -or- [Tight] Pack the items to the side of the ship with the suit rack.
# Setting type: String
# Default value: Tight
ItemGrouping = Tight

## List of items separated by comma that will be automatically placed in the storage container on ship cleanup.
# Setting type: String
# Default value: Whoopie,Key,Flashlight,StunGrenade
ClosetLocationOverride = Whoopie

## List of items separated by comma that will be ignored on sorting.
# Setting type: String
# Default value: 
SortingDisabledList = Shotgun,Shovel,Shell,Radar,Key,Flashlight,StunGrenade,Lockpicker

## Drop a held item and set the position of this type of item.
# Setting type: String
# Default value: <Keyboard>/j
DropAndSetObjectTypePositionKey = <Keyboard>/j

## If [Enabled], pressing J (or what ever keybind from DropAndSetObjectTypePositionKey) will set an objects item type location for organization
# Setting type: String
# Default value: Disabled
UseItemTypePlacementOverrides = Disabled

## If [Enabled], pressing J (or what ever keybind from DropAndSetObjectTypePositionKey) with a one handed object will set all one handed objects location for organization
# Setting type: String
# Default value: Disabled
UseOneHandedPlacementOverrides = Enabled

## If [Enabled], pressing J (or what ever keybind from DropAndSetObjectTypePositionKey) with a two handed object will set all two handed objects location for organization
# Setting type: String
# Default value: Disabled
UseTwoHandedPlacementOverrides = Disabled
```

**Comment by bozzobrain** [comment]
I think I found the bug. Should be fixed in v3.2.3.
Wasnt storing the one handed object locations correctly, was storing by name of object instead of the onehanded property. Give this a try.

**Comment by jcsnider** [comment]
Working really well for me. Only other request for me personally in respect to this feature would be for our positioning preferences to persist across saves and multiple launches of the game.

**Comment by bozzobrain** [comment]
I made an attempt at this. But I can try to improve this potentially. Are you referring to the one-handed vs. two-handed items, or more the individual types. Is there an example of a situation that it doesnt work as expected?

**Comment by bozzobrain** [comment]
This feature has been added in V3.2.4
Thanks for the ideas!! Give it a try and break it so I can fix any bugs!
