### ISSUE TITLE
It seems with some other mods (will include code) the items arnt synced.

### ISSUE THREAD

**Issue by HiiJustin** [bozzobrain/LethalCompanyShipMaid#8]
Only host can see the items change position. When the other players press the (m) key it only causes a small burst of lag for some and nothing for others.

018d2633-87e2-f00c-34b2-8f248ba8a118

**Comment by bozzobrain** [comment]
First question is do all other players have the mod installed? I assume all players have the same mod-pack installed that you are playing with?

**Comment by bozzobrain** [comment]
I think I determined what the issue was. Release V3.2.5 should address this issue and resolve the lack of client/server communication.

Feel free to check back in to let me know if the issue is resolved.

**Comment by HiiJustin** [comment]
Thank you! Sorry I didn't see the response. Yes all players are running the
same mods :)

**Comment by bozzobrain** [comment]
All good. Keep me posted on any issues you may see in the new release. It's hard for me to test things in an online setting, so I usually farm it out to the community 😅

**Comment by HiiJustin** [comment]
Will do, thanks!
