### ISSUE TITLE
Bug: Item Positioning for Magic 7 Ball

### ISSUE THREAD

**Issue by jcsnider** [bozzobrain/LethalCompanyShipMaid#9]
For some reason the item positioning overrides are not saving for the Magic 7 Ball, all other items it seems to work fine.

**Comment by bozzobrain** [comment]
Very interesting! I will look at this and see if I can tell what is going on with this item. It may be a regex thing that is preventing matches on numbers. Will let you know when I have more information.

**Comment by bozzobrain** [comment]
Sure enough it was a regex error where I was not checking for numbers in the name of the object. This has been fixed. Thanks for the feedback!
